import StoreProvider from '@/utils/StoreProvider'
import Footer from './Footer'
import Nav from './Nav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecom MN',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Nav />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
